### PR TITLE
Update Scripting_reference.md

### PR DESCRIPTION
**Pull request by J-128**
Clean up and properly link the list of classes

### CODE REVIEW

**Review by Rusty-Box — CHANGES_REQUESTED** [review]
Please remove the `.md` from the linked pages. Otherwise navigating those pages becomes more troublesome.

**Comment by J-128** [comment]
That results in a 404 (at least from the edit preview), assuming you mean changing E.G. `* [AmbientSound](ScriptingAmbientSound.md)` to `* [AmbientSound](ScriptingAmbientSound)`.

**Comment by Rusty-Box** [comment]
That is due to the fact that while editing the file in the wiki repository it does try to link you to a page in the wiki of the wiki repository (as strange as that sounds) so obviously it won't find anything.

However once it is build into the actual wiki of SuperTux/supertux it will direct to the proper page.

Alternatively you can use ``[AmbientSound](https://github.com/SuperTux/supertux/wiki/ScriptingAmbientSound)`` instead.

**Comment by J-128** [comment]
...That is confusing.  Alright, I'll push those changes.

**Review by Rusty-Box — APPROVED** [review]

**Pull request merged**
